on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout Config
        uses: actions/checkout@v4
        with:
          path: config

      - name: Checkout ZMK
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          ref: main
          path: zmk-workspace # ZMK本体をここに落とす

      - name: West Init & Update
        run: |
          cd zmk-workspace
          # appフォルダにあるwest.ymlを直接指定して初期化
          west init -l app/
          west update
          west zephyr-export

      - name: Build Right
        run: |
          cd zmk-workspace
          west build -s app -b xiao_ble -- \
            -DSHIELD=roBa_R \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config/config" \
            -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}/config"

      - name: Copy Artifact
        run: cp zmk-workspace/build/zephyr/zmk.uf2 roBa_R.uf2

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: "*.uf2"
